feature: default cookie banner
Jam3/nextjs-boilerplate pull request #127
Opened 2021-07-26 15:43 UTC by DonghyukJacobJang

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [ ] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Did you test your solution?**

- [ ] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description

## Solution Description

## Side Effects, Risks, Impact

- [ ] N/A

**Aditional comments:**

2021-08-24 22:53 UTC, namniak requested changes
just a minor note about labels

2021-08-24 22:53 UTC, namniak commented on src/components/CookieBanner/CookieBanner.js
> +                <label>necessary</label>
I believe all labels need to hafe `for` attribute with the id of the element they describe
with react it's be `htmlFor="cookie-necessary"` see https://reactjs.org/docs/accessibility.html#labeling

2021-09-23 14:30 UTC, DonghyukJacobJang commented
@namniak Iran suggested to not add `noscript` tag at all because it is against the privacy law and very edge cases.

2021-09-23 14:31 UTC, merged

2021-09-23 14:47 UTC, namniak commented
Agree - that's the best approach