[Feature] Responsive Image Component (Serverless Image Handler)
Jam3/nextjs-boilerplate pull request #227
Opened 2022-05-12 15:46 UTC by grez96

wip

2022-06-14 21:07 UTC, namniak requested changes
@edgardz you mentioned there are some issues with resizing - please provide @grez96 with details to test and address

2022-06-14 21:07 UTC, namniak commented on src/components/ResponsiveImage/ResponsiveImage.tsx
> +    bucket: process.env.NEXT_PUBLIC_SERVERLESS_IMAGE_HANDLER_BUCKET,
as was detected by @edgardz bucket cause issues with the new CI/CD promotion approach where artifacts just move from one stage to another.
you actually don't need the bucket specified as AWS Serverless Image has it set up based on it's own env variable for each stage. So FE can manipulate it but it's optional and certainly causes issues for pre-rendered pages and artifact promotion.

@grez96 to be removed and tested

2022-06-15 14:55 UTC, grez96 commented on src/components/ResponsiveImage/ResponsiveImage.tsx
> +    bucket: process.env.NEXT_PUBLIC_SERVERLESS_IMAGE_HANDLER_BUCKET,
Great find! I have tested removing the bucket parameter in my sandbox repository and it works perfectly! I have updated this PR with the change.

2022-10-14 20:59 UTC, iranreyes commented
@grez96 Closing this PR in favor of https://github.com/Jam3/nextjs-boilerplate/pull/269, please review if we missed something

2022-10-14 20:59 UTC, closed without merging