fix: replace isWindow with jam3 detect
Jam3/nextjs-boilerplate pull request #231
Opened 2022-06-06 18:33 UTC by DonghyukJacobJang

Jira Ticket ID: <JIRA Ticket ID> 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [ ] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Did you test your solution?**

- [ ] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description

## Solution Description

## Side Effects, Risks, Impact

- [ ] N/A

**Aditional comments:**

2022-06-07 15:52 UTC, namniak commented on src/pages/_app.tsx
> +if (device.browser) {
whenever an external file is imported, Webpack won't be able to evaluate its value as false (even when it's resolved as false value in that separate file because Webpack works on a file-by-file basis).
so this will work as condition FE but Webpack won't strip out these dependencies from the prod bundle which should be seen in the bundle analyzer.

for the same reason we can't move `isBrowser = typeof window !== 'undefined'` or `isDev = process.env.NODE_ENV === 'development'` into settings as they have to be used inline or defined at the top of each file otherwise it's never false from Webpack POV at the build time


so in this case `default-passive-events` and `focus-visible` will make it to the `server` bundle.

2022-06-07 16:35 UTC, DonghyukJacobJang commented on src/pages/_app.tsx
> +if (device.browser) {
I remembered your concerns about webpack.

I don't you if you had a chance to look at `@jam3/detect` repo and how `browser` and `node` instances are initiated. As far as I see, I believe this would work because the condition is based on `OS` platfrom. [reference link](https://github.com/Jam3/detect/blob/master/src/index.ts#L170)

Because of my short experience with webpack, I was not able to test your concern. Would you mind guiding me how to test the webpack case?

2022-06-09 12:32 UTC, DonghyukJacobJang commented on src/pages/_app.tsx
> -if (isBrowser) {
Removing this condition is fine. Having them without this condition threw a `window is undefined` error a long time ago. It does not occur anymore. In addition to that, those module must be added to the production build too.

2022-06-09 14:27 UTC, namniak commented on src/components/Layout/Layout.tsx
> +      {!isProd && <AppAdmin />}
i think a lot of people prefer to show it on dev/staging otherwise admin panel is kinda useless if it's only on local so I suggest to keep NEXT_PUBLIC_ENVIRONMENT vs NODE_ENV check

2022-06-09 14:52 UTC, DonghyukJacobJang commented on src/components/Layout/Layout.tsx
> +      {!isProd && <AppAdmin />}
good find. I made a mistake on this.

2022-06-13 19:17 UTC, alemesa submitted a review, later dismissed
Looks good @DonghyukJacobJang I tested it locally and different builds, not sure about the webpack resolution tho, might be good to wait for Vadim confirmation there

2022-06-14 20:49 UTC, namniak requested changes

2022-06-14 20:49 UTC, namniak commented on src/pages/_app.tsx
> +    if (!isProd && window.location.href.indexOf('?nostat') === -1) {
because it's not inline condition webpack will require anything that it placed here in the SSR `_app.js`
 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/4369064/173684106-ebb21cb6-1def-4458-8e8f-33d254a328b9.png">

if we want to exclude this, it needs to stay with inline `process.env.NODE_ENV !== 'production'` condition rather than using `isProd` evaluated in a separate file as we proved Webpack works line-by-line in this case when stripping code

test with `npm run build:ssr` and look at `.next/server/pages/-app.js`

2022-06-14 20:49 UTC, namniak commented on src/utils/why-did-you-render.ts
> +if (isDev && device.browser) {
same thing here - this won't be excluded from SSR without inline condition
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/4369064/173684898-b9d7b54d-e50e-40eb-8112-fc0f51ed9db9.png">

test with `npm run build:ssr` and look at `.next/server/pages/-app.js`

2022-06-14 20:49 UTC, namniak commented on src/utils/why-did-you-render.ts
> +if (isDev && device.browser) {
this will actually retain in `_app` client chunk to which we don't want
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/4369064/173685399-a30334db-532e-4496-9ae8-b0d82fb36e6c.png">

test with `npm run build:static` and npm bundle analyzer enabled
 
yu need to use import vs require - what you did for stats so that it stays in it's own chunk

2022-06-15 12:31 UTC, DonghyukJacobJang commented on src/utils/why-did-you-render.ts
> +if (isDev && device.browser) {
I tried to lazy load the `why-did-you-render` library and it failed due to the way of its mechanism. To secure and clean our production bundle, I am going to put the condition back which is `process.env.NODE_ENV === 'development'`.

2022-06-15 14:58 UTC, namniak approved these changes

2022-06-16 11:11 UTC, merged