PATCH 2: WIP
Jam3/nextjs-boilerplate pull request #291
Opened 2023-05-19 19:05 UTC by edgardz

- Update AppAdmin
- Use CircleCI pipeline number as build number
- Runtime environment detection (since we are using trunk based development, we cannot rely on env vars to detect the environment)
- Move Svgs to separate folder

2023-05-19 19:08 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-bae8179.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-05-19 19:12 UTC, edgardz commented
TIP: To bypass the preview credentials, use this link https://test%20env:password@preview-bae8179.dev.nextjs-boilerplate.jam3.cloud.jam3.net/

2023-05-25 20:56 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-903b4e4.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-05-25 21:04 UTC, gm-santos commented on src/data/config.json
> +{
this is awesome

2023-05-26 01:00 UTC, alemesa submitted a review, later dismissed
amazing!

🧑‍🍳😙🤌

2023-05-26 15:57 UTC, gm-santos commented on src/components/Layout/Layout.tsx
> +    const transitionTimeline = gsap.timeline()
🤯

2023-05-26 16:07 UTC, gm-santos submitted a review, later dismissed
transition in/out when navigate 🤯

2023-05-26 21:16 UTC, edgardz commented on src/components/Head/Head.tsx
>        {process.env.NODE_ENV === 'development' && (
The Head component is a bit different. Everything here must be rendered server side so the crawlers have the correct information when they load the HTML. Since we are using a trunk approach now, it means we have a single build for all envs, so the most we can do is detect if we are running the application on dev or production mode. We cannot detect the runtime environment at build time.

2023-05-26 21:18 UTC, edgardz commented on src/components/AppAdmin/AppAdmin.tsx
> +  const version = useMemo(() => process.env.NEXT_PUBLIC_VERSION_NUMBER || '', [])
Actually. We should! 😅

2023-05-26 21:29 UTC, alemesa commented
looking great, I cloned it and played around a bit

found only one more thing @edgardz, the cookie banner is not clickable

maybe we can just add in the `$elements` array => `cookie` after `pages`
and then just `@include z-index(cookie)`

2023-06-01 16:21 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-b758c1c.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-01 19:01 UTC, alemesa approved these changes
✨

2023-06-01 19:05 UTC, alemesa commented on .storybook/intro/Svg.stories.tsx
> +            key={icon.name}
sonar is pretty useless sometimes 💀

2023-06-02 14:37 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-b4579c4.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-05 15:58 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-cbf6722.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-17 18:45 UTC, namniak requested changes
@edgardz we need to change back the assets folder and make sure `public/assets` and  `public/favicons` are bac under `public/common`.
This was done for a reason as we have CloudFront `/common` behavior with a specific caching policy attached

2023-06-17 19:45 UTC, namniak requested changes

2023-06-17 19:45 UTC, namniak commented on src/components/PageHome/PageHome.module.scss
> +  opacity: 0;
same

2023-06-17 19:45 UTC, namniak commented on src/components/PageNotFound/PageNotFound.module.scss
> +  opacity: 0;
same

2023-06-17 19:45 UTC, namniak commented on src/components/PageUnsupported/PageUnsupported.module.scss
> +  opacity: 0;
same

2023-06-17 19:45 UTC, namniak commented on .circleci/scripts/deploy.sh
> +aws s3 sync ./favicons s3://${S3_ORIGIN_BUCKET}/favicons --metadata-directive 'REPLACE' --cache-control max-age=31536000,public ${DELETE_OLD_FILES}
revert paths in this file

2023-06-17 19:45 UTC, namniak commented on .storybook/manager-head.html
> +<link rel="shortcut icon" href="favicons/favicon.ico" />
pls revert

2023-06-17 19:45 UTC, namniak commented on .storybook/manager.ts
> +    brandImage: '/favicons/favicon-32x32.png'
pls revert

2023-06-17 19:45 UTC, namniak commented on public/favicons/site.webmanifest
> +      "src": "/favicons/favicon-192x192.png",
pls revert this file

2023-06-17 19:45 UTC, namniak commented on src/pages/_app.tsx
> +    window.history.scrollRestoration = 'manual'
why do we wanna do that?
this will prevent page restoration when you use the browser's back button which is pretty bad for the cases when you are on the blog page and click one of the blog cards then use browser back button and expect to end up where you were in the grid but you end up at the hero instead

2023-06-17 19:45 UTC, namniak commented on src/pages/_app.tsx
> +    }).observe(document.head, { subtree: true, attributeFilter: ['media'] })
We initially saw this issue back in 2020 and we had this fix added to one of the projects. is it still an issue? Haven't seen it in a while. I guess it might still happen in the case when the route changes and you still have the old page on the screen animating out in a transition group - we just probably didn't have this case for a long time

2023-06-17 19:45 UTC, namniak commented on src/data/config.json
> +    "gtmIds": { "prod": "GTM-0000000", "stage": "GTM-0000000", "dev": "GTM-0000000", "local": "" }
i suggest also adding GTM params per env as we recently often have one GTM property where ID is the same but params a re different based on the environments

2023-06-17 19:45 UTC, namniak commented on src/utils/analytics.tsx
> +        })(window,document,'script','dataLayer', '${gtmId}');
add params to the URL is case it's needed

2023-06-17 19:45 UTC, namniak commented on src/pages/_document.tsx
> +
pls add the code back it's a much better approach than adding opacity 0 to page and navs. this is actually doing what it's supposed to do - have all content visible on the server (e.g. with disabled JS) and removes that flash if FE is detected as the call is added to the document so the whole thing is hidden until the app kicks in and removes this class

2023-06-17 19:45 UTC, namniak commented on src/utils/set-body-classes.ts
> +import ResizeService from '@/services/resize'
please add the static HTML back. it's disabled by default if you don't want it but I actually recommend enabling that by default rather than removing

with the change made in this PR you's always see a blank page with JS disabled when buit and served:
<img width="857" alt="image" src="https://github.com/Jam3/nextjs-boilerplate/assets/4369064/5aad45ea-c7ef-4ef6-a57a-e22d0d513c5b">

2023-06-19 13:37 UTC, edgardz commented
@namniak Oh! I was not aware there was a logic coupling with code from another repo!

2023-06-19 14:28 UTC, edgardz commented on src/components/Nav/Nav.module.scss
> +  opacity: 0;
Actually, when JS is disabled a proper <noscript> screen should be rendered.

2023-06-19 14:30 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-2d16811.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-19 14:42 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-6eac162.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-19 14:45 UTC, edgardz commented on src/components/PageAbout/PageAbout.module.scss
> +  opacity: 0;
The past solution was still prone to FOUC on slow connections since it requires the JS to load and be executed in order to hide content. The new approach brings all pages hidden by default and unhide them when the JS kicks in. For the case of JS disabled browsers, we render a proper <noscript> screen.

2023-06-19 14:48 UTC, edgardz commented on src/pages/_app.tsx
> +    window.history.scrollRestoration = 'manual'
This prevents the page from scrolling before the transition out ends. If we don't have this, the scroll would jump before the current page have transitioned out.

2023-06-19 14:48 UTC, edgardz commented on src/pages/_app.tsx
> +    }).observe(document.head, { subtree: true, attributeFilter: ['media'] })
Yup. This is here because of page transitions.

2023-06-19 15:02 UTC, edgardz commented on src/utils/analytics.tsx
> +        })(window,document,'script','dataLayer', '${gtmId}');
Refactored this util to be a service.

2023-06-19 15:03 UTC, edgardz commented on src/pages/_document.tsx
> +
This solution is prone to FOUC on slow connections as mentioned before.

2023-06-19 15:05 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-f03ca4e.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-06-19 15:05 UTC, edgardz commented on src/utils/set-body-classes.ts
> +import ResizeService from '@/services/resize'
Now you see this:
![image](https://github.com/Jam3/nextjs-boilerplate/assets/97924/2b8811b4-2489-4641-828b-30c7b5cfc3be)

2023-06-19 18:51 UTC, namniak commented on src/pages/_document.tsx
> +
keep in mind`hideStaticHtml` is set to `false` out of the box so there's def hydration visible but with that on it's better

2023-06-19 18:58 UTC, namniak commented on src/utils/set-body-classes.ts
> +import ResizeService from '@/services/resize'
yes let's discuss this in the future
@iranreyes @DonghyukJacobJang @edgardz we need to decide what the future most common scenario is and just agree on the approach
both approaches have minor issues but for majority of the demographic either way works and NO-JS splash screen is less work compared to making static pages look good for every single component on it and with relatively small number of crawlers not executing JS maybe that's ok to sacrifice that? I'm 50/50 on this when thinking of different types of apps

2023-06-19 19:02 UTC, namniak commented on src/data/config.json
> +    "gtmIds": { "prod": "GTM-0000000", "stage": "GTM-0000000", "dev": "GTM-0000000", "local": "" }
lovely!

2023-07-21 15:54 UTC, edgardz commented on src/utils/set-body-classes.ts
> +import ResizeService from '@/services/resize'
Added `supportsNoJs` flag to data/config.json. This will allow us to chose the behavior depending on the project. if it is set to true, pages will not be hidden by default.

2023-07-21 15:55 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-b003b7d.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-07-21 19:16 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-9a2c62c.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-07-21 20:22 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-6cff671.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-07-22 21:27 UTC, namniak requested changes
Tested new changes and we are almost there!

2023-07-22 21:27 UTC, namniak commented on src/pages/_document.tsx
> +        {config.supportsNoJs && (
@edgardz I don't think it needs to be connected to `supportsNoJs`.
the idea of `hideStaticHtml` was that with JS available HTML is hidden until the app kicks in and unhides it so there's no static flash while  `supportsNoJs` needs to only control `ScreenNoScript` functionality.

Injection of these particular styles still needs to be based on `typeof window !== 'undefined'` condition and apply regardless of `supportsNoJs` value.
idk if we wanna always do that by default (ideally yes) but If we don't then we need to re-introduce a separate `hideStaticHtml` option.
if we introduce a separate flag then this only needs to apply based on the flag in Layout.js
```
  // make sure the page us un-hidden once application kicks in
  useEffect(() => {
    gsap.set(document.documentElement, { autoAlpha: 1 })
    gsap.set(rootRef.current, { autoAlpha: 1 })
  }, [])
```

I know that we now hide the pages with JS on mount via hook but the difference is that those would be only executed once the whole app kicks in (meaning there will be a flash until then) while the hide should apply asap which is what the script injection will take care of.

2023-07-22 21:27 UTC, namniak commented on src/components/Layout/Layout.tsx
> +    gsap.set(document.documentElement, { autoAlpha: 1 })
See comment about `hideStaticHtml` condition for this.

2023-07-22 21:27 UTC, namniak commented on src/components/Layout/Layout.module.scss
> +  }
based on testing this doesn't seem to apply when `supportsNoJs` is set to `true`.
Also not sure it's needed if we already apply hide to the whole HTML via script

2023-07-22 21:27 UTC, namniak commented on src/components/Layout/Layout.tsx
> +    gsap.set(rootRef.current, { autoAlpha: 1 })
probably extra see comment above

2023-07-22 21:27 UTC, namniak commented on src/components/Layout/Layout.tsx
> +
this works well but there's a catch it stores one page at a time and loses the position once you scroll on the new page. e.g. 

- land on about scroll, go to index, use the back button - about is restored as expected
- land on about scroll, go to index and scroll, use the back button - about page position is lost.

Native page restoration remembers the position per page and switching between two pages using the browser's back button on each restore position independently.

It might be worth extending Redux functionality (which already stores `prevRoute`) and store page positions on leave and then applying it here on the Layout level on route change if it's `going back`

2023-07-24 16:24 UTC, jam3-devops commented
[AUTOMATED] Latest version has been pushed to preview.

Preview deployed at https://preview-7fb89b6.dev.nextjs-boilerplate.jam3.cloud.jam3.net

2023-07-24 18:01 UTC, namniak approved these changes
Thanks, @edgardz!
A lot of great stuff here - appreciate your work.
Let's 🚢 it

@DonghyukJacobJang let us know if you wanna have a look first.
I think this is important to get this in asap

2023-07-24 19:18 UTC, alemesa approved these changes
🔥 🚀

2023-07-25 16:50 UTC, merged