fix: track window undefined and default gtm code snippet
Jam3/nextjs-boilerplate pull request #91
Opened 2021-03-18 03:34 UTC by DonghyukJacobJang

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [ ] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

**Did you test your solution?**

- [ ] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description

## Solution Description

## Side Effects, Risks, Impact

- [ ] N/A

**Aditional comments:**

2021-05-29 18:23 UTC, namniak requested changes

2021-05-29 18:23 UTC, namniak commented on src/utils/detect.js
> +export const isBrowser = typeof window !== 'undefined';
I would avoid exposing this via export because it will encourage people to use that instead of checking `typeof window !== 'undefined';` in place. this creates differences with webpack export and server bundle.

Webpack is doing things file-by-file that means if variable is evaluated outside the file, it will be treated as non-falsey (because it was declared globally) but webpack doesn't know the value so it will include the chunk of code in the server bundle even though it won't execute it

2021-05-29 18:23 UTC, namniak commented on src/utils/track.js
> +if (isBrowser) window.dataLayer = window.dataLayer || [];
see the above message. it doesn't make a lot of difference here but people will get used to using it assuming that
```
if (isBrowser) {
  // some FE code
  // some FE require
}
```
wouldn't be included in the server bundle but it would unlike using 
```
if (typeof window !== 'undefined') {
  // some FE code
  // some FE require
}
```

2021-06-23 15:51 UTC, DonghyukJacobJang commented
@namniak Thanks for your feedback! it has been applied!

2021-06-23 16:12 UTC, namniak commented on src/components/Head/Head.js
> +      {GtmScript()}
@DonghyukJacobJang is there a preference in adding this here vs in the `_document`?
is it the order of scripts being loaded?
also I always add it to the document and not 100% sure if having that in the component that is used in every page will cause extra initialization on route change

2021-06-23 17:01 UTC, DonghyukJacobJang commented on src/components/Head/Head.js
> +      {GtmScript()}
yeah. it was because of the order of meta tags. fortunately, it will not re-init with our current setup. I can run more test.

2021-06-23 17:45 UTC, namniak commented on src/components/Head/Head.js
> +      {GtmScript()}
then lgtm!

2021-06-23 17:45 UTC, namniak approved these changes

2021-06-24 14:29 UTC, merged